# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eafbcb878e68b2f07d41ac475f90f5d8d1898138544a0c6d9754409c9a7c0bfa98d2de7770be8e2b3fc170aab3539236e0e800497dcb9fb1f7589c2133ab289b

test:
  secret_key_base: 31c46858b145fc9b35aa0543d65e27cffb72957b97c7b5bf0be5c5b86dc9ea93f988b5c4ed46d2b41f8108f2e8f16db9f4372a82fd29eea9841a848669a1bc9c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
